### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by MorgothSauron** [linuxserver/docker-pyload#13]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

pyload feels extremely low, but checking the container log I can see that broken pipe errors are contstantly logged

------------------------------

## Expected Behavior
No error

## Current Behavior
Docker keeps logging the following exception

```
pyload    | Traceback (most recent call last):
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
pyload    |     self.finish_response()
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
pyload    |     self.write(data)
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
pyload    |     self.send_headers()
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
pyload    |     self.send_preamble()
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 194, in send_preamble
pyload    |     'Date: %s\r\n' % format_date_time(time.time())
pyload    |   File "/usr/lib/python2.7/socket.py", line 328, in write
pyload    |     self.flush()
pyload    |   File "/usr/lib/python2.7/socket.py", line 307, in flush
pyload    |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
pyload    | error: [Errno 32] Broken pipe
```
## Steps to Reproduce

- Create compose file `docker-compose.yml`:
- Run `docker-compose up`
- Watch the output

## Environment
**OS:** Manjaro ARM     
**CPU architecture:** arm64
**How docker service was installed:**      
Installed from the Manjaro repository (`pacman -Sy docker`)

```
$ docker version
Client:
 Version:           19.03.8-ce
 API version:       1.40
 Go version:        go1.14
 Git commit:        afacb8b7f0
 Built:             Tue Mar 17 23:37:06 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14
  Git commit:       afacb8b7f0
  Built:            Tue Mar 17 23:36:36 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.3.3.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Command used to create docker container (run/create/compose/screenshot)

```
version: "3.2"
services:
  pyload:
    image: linuxserver/pyload
    container_name: pyload
    hostname: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - config:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - ${HOSTIP}:8000:8000
      - ${HOSTIP}:7227:7227 #optional
    restart: unless-stopped
volumes:
    config:
```

## Docker logs

```
pyload    | Traceback (most recent call last):
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
pyload    |     self.finish_response()
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
pyload    |     self.write(data)
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
pyload    |     self.send_headers()
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
pyload    |     self.send_preamble()
pyload    |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 197, in send_preamble
pyload    |     self._write('Server: %s\r\n' % self.server_software)
pyload    |   File "/usr/lib/python2.7/socket.py", line 328, in write
pyload    |     self.flush()
pyload    |   File "/usr/lib/python2.7/socket.py", line 307, in flush
pyload    |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
pyload    | error: [Errno 32] Broken pipe
pyload    | Traceback (most recent call last):
pyload    |   File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
pyload    |     self.process_request(request, client_address)
pyload    |   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
pyload    |     self.finish_request(request, client_address)
pyload    |   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
pyload    |     self.RequestHandlerClass(request, client_address, self)
pyload    |   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
pyload    |     self.finish()
pyload    |   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
pyload    |     self.wfile.close()
pyload    |   File "/usr/lib/python2.7/socket.py", line 283, in close
pyload    |     self.flush()
pyload    |   File "/usr/lib/python2.7/socket.py", line 307, in flush
pyload    |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
pyload    | error: [Errno 32] Broken pipe
```

**Comment by MorgothSauron** [comment]
I tested the same docker-compose file on Fedora 31 with podman v1.8.2 and it works without error.
